### ISSUE TITLE
Plan selection doesn't work on Apply Now page

### ISSUE THREAD

**Issue by bluet** [OSSPlanet/OSSPlanet.github.io#13]
http://ossplanet.net/#section5

default mail "Subject/Title" in Step 2 should be changed at realtime when Plan changed.
But now it doesn't work.

**Comment by bluet** [comment]
@focaaby @passerbyid can you help on fixing this?

**Comment by YuerLee** [comment]
Fixed.
- Commit: 7de088e12f4464f6169f17ffd3def26b7360ef14
