### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by eloaders** [OSSPlanet/OSSPlanet.github.io#14]
I need to add a logo to promote your website. Do you have a logo, banner, or anything else?

**Comment by bluet** [comment]
Hi @eloaders , We finally have our Logo here https://drive.google.com/drive/u/0/folders/0B0VxHH0sjPWGRHkybVViX1g2ZEk
Thanks a lot. :-)

BTW, I can't open http://i-nex.linux.pl/. Is it down?

**Comment by eloaders** [comment]
Thank you very much
I will add your logo on the home page of my program. I have a server from you, it does not work :( Since I do not have time now

**Comment by bluet** [comment]
:+1: 

@eloaders  Do you need my help setting up your server?
If yes, just let me know. :-)

**Comment by bluet** [comment]
close due to no further activities
