### ISSUE TITLE
Service Monitoring

### ISSUE THREAD

**Issue by bluet** [OSSPlanet/OSSPlanet.github.io#3]
為提昇服務品質，機房加設了 PHP Server Monitor 協助監控各服務，並在異常時會即時通知。
還請有需要的各位回覆、協助填寫。

管理者名稱 + Email Addr：(可以多人)
手機號碼：(目前簡訊功能尚未完成，但請先提供)

---

(若需監控多個服務，請自行將下列欄位複製使用)
Server / Service Name:
Type: (Website / Service / Protocol)
Domain / IP + Port:

**Comment by bluet** [comment]
ping @pellaeon @petercpg @irvin @MingcongBai @Yexiaoxing

**Comment by petercpg** [comment]
# MozTW

管理者名稱 + Email Addr：Peter Chen <petercpg@mail.moztw.org>; MozTW Admins <admin@mail.moztw.org>
手機號碼：+886988820229

Server / Service Name: MozTW.org
Type: Website
Domain / IP + Port: https://moztw.org:443/

Server / Service Name: MozTW Forum
Type: Website
Domain / IP + Port: https://forum.moztw.org:443/


感謝！

**Comment by bluet** [comment]
move issue to https://github.com/OSSPlanet/OSSPlanet/issues/2
